### PR TITLE
Fix panel()->user - php error

### PR DESCRIPTION
**Pull request by dschenk**
**panel()->user** does not exist. It should be **panel()->user()**

### CODE REVIEW

**Comment by omz13** [comment]
Thanks for spotting this. It was closed in 0.2.

**Comment by dschenk** [comment]
Did you forget to merge the commit? The bug is still present in master and 0.2

**Comment by dschenk** [comment]
On another note: have you considered using semantic versioning for the project? See http://semver.org/

**Comment by omz13** [comment]
Fixed. Thanks.

**Comment by dschenk** [comment]
Cool, thanks!
Would have been nice if you could have merged my pull-request though, then I would have gotten some contribution credits.

**Pull request closed without merging**
